"""Refresh the static archives catalog by scanning the ESIOS API.

Usage:
    uv run python -m esios.data.catalogs.archives.refresh

Scans archive IDs 1-200 against the live API and regenerates catalog.py.
"""

from __future__ import annotations

import sys
from pathlib import Path


def scan_archives(max_id: int = 200) -> dict[int, dict[str, str]]:
    """Scan ESIOS API for all accessible archives."""
    from esios import ESIOSClient

    client = ESIOSClient()
    catalog: dict[int, dict[str, str]] = {}

    for i in range(1, max_id + 1):
        try:
            data = client.get(f"archives/{i}")
            a = data.get("archive", {})
            catalog[i] = {
                "name": a.get("name", ""),
                "description": a.get("description", ""),
                "horizon": a.get("horizon", ""),
                "archive_type": a.get("archive_type", ""),
            }
        except Exception:
            continue

    return catalog


def generate_catalog_py(catalog: dict[int, dict[str, str]]) -> str:
    """Generate the catalog.py source code."""
    lines = [
        '"""Static catalog of ESIOS archives.',
        "",
        "Auto-generated by refresh.py — do not edit manually.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "ARCHIVES_CATALOG: dict[int, dict[str, str]] = {",
    ]

    for id_ in sorted(catalog):
        entry = catalog[id_]
        name = entry["name"]
        desc = entry["description"].replace('"', '\\"')
        horizon = entry["horizon"]
        atype = entry["archive_type"]
        lines.append(
            f'    {id_}: {{"name": "{name}", "description": "{desc}", '
            f'"horizon": "{horizon}", "archive_type": "{atype}"}},'
        )

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    from esios.data.catalogs.archives.catalog import ARCHIVES_CATALOG

    old_ids = set(ARCHIVES_CATALOG.keys())

    print(f"Scanning ESIOS API for archives (IDs 1-200)...")
    catalog = scan_archives()
    new_ids = set(catalog.keys())

    # Diff summary
    added = new_ids - old_ids
    removed = old_ids - new_ids

    print(f"\nFound {len(catalog)} archives (was {len(old_ids)})")
    if added:
        print(f"  Added: {sorted(added)}")
    if removed:
        print(f"  Removed: {sorted(removed)}")
    if not added and not removed:
        print("  No changes in archive IDs.")

    # Write catalog.py
    catalog_path = Path(__file__).parent / "catalog.py"
    catalog_path.write_text(generate_catalog_py(catalog))
    print(f"\nWrote {catalog_path}")


if __name__ == "__main__":
    main()
